import { NextRequest, NextResponse } from 'next/server'
import { getPayload } from 'payload'
import config from '@/payload.config'
import { getPayment } from '@/lib/gopay'
import { sendOrderConfirmation } from '@/lib/email'
import { ensureInvoice } from '@/lib/invoice'

// GoPay delivers payment-state notifications as HTTP GET ?id=<paymentId>.
// POST is kept for manual replays.
export { handleNotification as GET, handleNotification as POST }

async function handleNotification(req: NextRequest) {
  const { searchParams } = new URL(req.url)
  const gopayId = searchParams.get('id')
  if (!gopayId) return NextResponse.json({ error: 'missing id' }, { status: 400 })

  const payload = await getPayload({ config })

  // Pre-check: verify gopayId maps to a pending order before hitting GoPay API.
  // Prevents API abuse and unnecessary token usage from arbitrary webhook POSTs.
  const { docs } = await payload.find({
    collection: 'orders',
    where: { and: [{ gopayId: { equals: gopayId } }, { status: { equals: 'pending' } }] },
    limit: 1,
  })
  if (!docs.length) return NextResponse.json({ ok: true })

  const payment = await getPayment(gopayId)
  if (payment.state !== 'PAID') return NextResponse.json({ ok: true })

  const order = docs[0]

  await payload.update({ collection: 'orders', id: order.id, data: { status: 'paid' } })

  // Invoice (faktúra): generated once per order, stored outside public/, sent
  // as an attachment and via a tokenized link. Failure must not break the
  // payment flow — it is logged and the invoice can be regenerated by link.
  let invoice: Awaited<ReturnType<typeof ensureInvoice>> | null = null
  try {
    invoice = await ensureInvoice(payload, order.id)
  } catch (err) {
    console.error('[webhook] invoice generation failed:', err)
  }

  // Packeta shipments are created MANUALLY by the operator (in the Packeta client,
  // using the pickup point stored on the order) — deliberately not automated.
  // The operator then sets the order to "shipped" in the admin.
  try {
    await sendOrderConfirmation({
      to: (order.customer as { email: string }).email,
      orderNumber: order.orderNumber as string,
      items: order.items as Array<{ title: string; configuration: Record<string, string>; quantity: number; unitPrice: number }>,
      totalAmount: order.totalAmount as number,
      currency: order.currency as string,
      packetaPointName: (order.shipping as { packetaPointName: string }).packetaPointName,
      locale: order.locale as string,
      ...(invoice ? {
        invoiceUrl: `${process.env.NEXT_PUBLIC_APP_URL}/api/invoices/${invoice.invoiceToken}`,
        invoicePdf: { filename: `${invoice.invoiceNumber}.pdf`, content: invoice.pdf },
      } : {}),
    })
  } catch (err) {
    console.error('Email send failed:', err)
  }

  return NextResponse.json({ ok: true })
}
